server:
  port: 0
spring:
  application:
    name: api-margins

eureka:
  instance:
    hostname: localhost
    instance-id: ${spring.application.name}:${spring.application.instance_id:${random.value}}
  client:
    registerWithEureka: true
    #No consume otros servicios
    fetchRegistry: false
    service-url:
      defaultZone: http://localhost:8761/eureka/
