server:
  port: 8081

spring:
  application:
    name: api-customer
  data:
    mongodb:
      username: usr-customer-mongo
      password: pwd-customer-mongo
      database: customer-dev-mongo
      port: 27017
      host: mongo-container
  jpa:
    hibernate.ddl-auto: update
    generate-ddl: true
    show-sql: true
  #jpa:
    #generate-ddl: true
    #hibernate:
      #enable_lazy_load_no_trans: true
      #event:
        #merge:
          #entity_copy_observer: allow
      #ddl-auto: update
    #properties:
      #hibernate:
        #dialect: org.hibernate.dialect.MySQL55Dialect
        #format_sql: true
    #show-sql: false
    #management:
      #endpoints:
        #web:
          #exposure:
            #git include=serviceregistry,health,info
info:
  application:
    name: api-customer


eureka:
  healthcheck:
    enabled: true
  instance:
    hostname: localhost
    instance-id: ${spring.application.name}:${spring.application.instance_id:${random.value}}
  client:
    registerWithEureka: true
    fetchRegistry: true
    service-url:
      defaultZone: http://localhost:8761/eureka/

resilience4j:
  retry:
    configs:
      default:
        max-retry-attempts: 3
        wait-duration: 1s
        retry-exceptions:
          - java.io.IOException
          - java.net.SocketTimeoutException
      instances:
        retryInscription:
          base-config: default
          max-retry-attempts: 5
          wait-duration: 2s
          retry-exceptions:
            - java.net.ConnectException
  circuit-breaker:
    configs:
      default:
        register-health-indicator: true
        sliding-window-size: 10
        minimum-number-of-calls: 5
        permitted-number-of-calls-in-half-open-state: 3
        wait-duration-in-open-state: 30s
        automatic-transition-from-open-to-half-open-enabled: true
        failure-rate-threshold: 50
    instances:
      checkCustomer:
        base-config: default
        sliding-window-type: COUNT_BASED
        sliding-window-size: 5
        wait-duration-in-open-state: 1m
        failure-rate-threshold: 20