server:
  port: 8081

spring:
  application:
    name: api-customer
  mongodb:
    embedded:
      version: 4.0.2
    data:
      mongodb:
        database: test
        port: 27017
  #jpa:
    #generate-ddl: true
    #hibernate:
      #enable_lazy_load_no_trans: true
      #event:
        #merge:
          #entity_copy_observer: allow
      #ddl-auto: update
    #properties:
      #hibernate:
        #dialect: org.hibernate.dialect.MySQL55Dialect
        #format_sql: true
    #show-sql: false
    #management:
      #endpoints:
        #web:
          #exposure:
            #git include=serviceregistry,health,info
info:
  application:
    name: api-customer

urlCheck: http://localhost:8083

eureka:
  instance:
    hostname: localhost
    instance-id: ${spring.application.name}:${spring.application.instance_id:${random.value}}
  client:
    registerWithEureka: true
    fetchRegistry: true
    service-url:
      defaultZone: http://localhost:8761/eureka/