server:
  port: 8086
spring:
  application:
    name: api-check
  datasource:
    driverClassName: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3307/checkAgro-dev
    username: usr-checkAgro
    password: pwd-checkAgro
  eureka:
    instance:
      hostname: localhost
      instance-id: ${spring.application.name}:${spring.application.instance_id:${random.value}}
    client:
      registerWithEureka: true
      fetchRegistry: true
      service-url:
        defaultZone=http://localhost:8761/eureka/
      enabled:
        false

  jpa:
    generate-ddl: true
    hibernate:
      enable_lazy_load_no_trans: true
      event:
        merge:
          entity_copy_observer: allow
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL55Dialect
        format_sql: true
        show-sql: false
        management:
          info:
            env:
              enabled = true
          endpoints:
            web:
              exposure:
                include=serviceregistry,health,info



